export const sceneManager = {
	SCENES: {
		PRELOAD: "PRELOAD",
		MAINMENU: "MAINMENU",
		GAME: "GAME",
		CONFIG: "CONFIG",
		RRSS: "RRSS",
		CONTROLS: "CONTROLS",
		CHARACTERSELECT: "CHARACTERSELECT"
	}
}
